openapi: 3.0.0
info:
  title: MyService
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /MyService/MyMethod:
    post:
      operationId: MyMethod
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MyRequest"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyResponse"
components:
  schemas:
    MyRequest:
      type: object
      required:
        - a
        - b
      properties:
        a:
          type: integer
        b:
          type: string
    MyResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
        message:
          type: string